/**
 * @(#)$CurrentFile
 *
 *<br> Copyright：Copyright (c) 2010
 *<br> @author XXXXX（XXXXX）
 *<br> 2010-05-01
 *<br> @version 1.0
 */

package com.easecom.system.web;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

import com.easecom.common.framework.struts.BaseForm;

/**
 * AbstractSysRole generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class SysRoleForm extends BaseForm {
	private String id;
	private String name;
	private String remark;
	private String roleurl;
	private String shopId;
	private boolean  ischoose; //给岗位分配角色时使用，判断该角色是否已经分配
	
	private int state;


	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public boolean isIschoose() {
		return ischoose;
	}

	public void setIschoose(boolean ischoose) {
		this.ischoose = ischoose;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public String getRoleurl() {
		return roleurl;
	}

	public void setRoleurl(String roleurl) {
		this.roleurl = roleurl;
	}

	public String getShopId() {
		return shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}
	
}